export const MUTEX_REQUEST_COOKIE = ".tail.rq";
export const MUTEX_RESPONSE_COOKIE = ".tail.rs";
export const CONTEXT_MENU_COOKIE = ".tail.cm";
export const QUERY_DEVICE = "qd";
export const INITIALIZE_TRACKER_FUNCTION = ".tail.js.init";
export const EVENT_HUB_QUERY = "var";
export const VARIABLES_QUERY = "usr";
export const CONTEXT_MENU_QUERY = "mnt";
//# sourceMappingURL=constants.js.map