import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
//import { ConfiguredTracker } from "./api/tailjs/ConfiguredTracker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const jsx = jsxRuntime.jsx as any;
// //(jsxRuntime as any).jsx = (...args: any) => (console.log(args), jsx(...args));

// const jsxs = jsxRuntime.jsxs as any;
// (jsxRuntime as any).jsxs = (...args: any) => (console.log(args), jsxs(...args));

// import jsxDevRuntime from "react/jsx-dev-runtime";

// const jsxDev = jsxDevRuntime.jsxDEV as any;
// (jsxDevRuntime as any).jsxDEV = (...args: any) => (
//   console.log(args), jsxDev(...args)
// );

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
