import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClientWhatever } from "./components/ClientWhatever";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Fasso = (props: any) => {
  return (
    <>
      <div>
        <ul>
          <li>Tisser</li>
        </ul>
      </div>
      <ClientWhatever />
    </>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      {/* <head>
        <ConfiguredTracker.Script strategy="html" />
        <script src="https://web.cmp.usercentrics.eu/modules/autoblocker.js"></script>
        <script
          id="usercentrics-cmp"
          src="https://web.cmp.usercentrics.eu/ui/loader.js"
          data-settings-id="VPy_v-VTfbxrX-"
          async
        ></script>
      </head> */}

      <body className={inter.className}>
        {/* <ConfiguredTracker> */}
        <Fasso foo={80} />
        {/* </ConfiguredTracker> */}
      </body>
      {/* <Script src="https://web.cmp.usercentrics.eu/modules/autoblocker.js" />
      <Script
        id="usercentrics-cmp"
        src="https://web.cmp.usercentrics.eu/ui/loader.js"
        data-settings-id="VPy_v-VTfbxrX-"
        async
      /> */}
    </html>
  );
}
