export declare const QUERY_DEVICE = "qd";
export declare const INITIALIZE_TRACKER_FUNCTION = ".tail.js.init";
export declare const INIT_SCRIPT_QUERY = "inito";
export declare const CLIENT_SCRIPT_QUERY = "opt";
export declare const EVENT_HUB_QUERY = "var";
export declare const VARIABLES_QUERY = "usr";
export declare const CONTEXT_NAV_QUERY = "mnt";
export declare const SCHEMA_QUERY = "$types";
export declare const BUILD_REVISION_QUERY: string;
export declare const SCOPE_INFO_KEY = "@info";
export declare const CONSENT_INFO_KEY = "@consent";
export declare const SESSION_REFERENCE_KEY = "@session_reference";
export declare const PATCH_EVENT_POSTFIX = "_patch";
export declare const CLIENT_STORAGE_PREFIX = "_tail:";
export declare const CLIENT_STATE_CHANNEL_ID: string;
export declare const CLIENT_CALLBACK_CHANNEL_ID: string;
